-- MySQL Script generated by MySQL Workbench
-- Сб 15 авг 2020 23:24:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sportcity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sportcity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportcity` ;
USE `sportcity` ;

-- -----------------------------------------------------
-- Table `sportcity`.`club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`club` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `name` VARCHAR(100) NOT NULL,
                                                  PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`sportsman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`sportsman` (
                                                       `id` INT NOT NULL AUTO_INCREMENT,
                                                       `name` VARCHAR(100) NOT NULL,
                                                       `club_id` INT NOT NULL,
                                                       PRIMARY KEY (`id`),
                                                       INDEX `fk_sportsman_club1_idx` (`club_id` ASC) ,
                                                       CONSTRAINT `fk_sportsman_club1`
                                                           FOREIGN KEY (`club_id`)
                                                               REFERENCES `sportcity`.`club` (`id`)
                                                               ON DELETE CASCADE
                                                               ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`coach` (
                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                   `name` VARCHAR(100) NOT NULL,
                                                   `sport` ENUM('football', 'tennis', 'hockey', 'volleyball', 'figureSkating', 'athletics') NOT NULL,
                                                   PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`competition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`competition` (
                                                         `id` INT NOT NULL AUTO_INCREMENT,
                                                         `name` VARCHAR(100) NOT NULL,
                                                         `beginning_date` DATE NOT NULL,
                                                         `finish_date` DATE NOT NULL,
                                                         `sport` ENUM('football', 'tennis', 'hockey', 'volleyball', 'figureSkating', 'athletics') NOT NULL,
                                                         PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`participation` (
                                                           `sportsman_id` INT NOT NULL,
                                                           `competition_id` INT NOT NULL,
                                                           PRIMARY KEY (`sportsman_id`, `competition_id`),
                                                           INDEX `fk_participation_competition1_idx` (`competition_id` ASC) ,
                                                           CONSTRAINT `fk_participation_sportsman1`
                                                               FOREIGN KEY (`sportsman_id`)
                                                                   REFERENCES `sportcity`.`sportsman` (`id`)
                                                                   ON DELETE CASCADE
                                                                   ON UPDATE CASCADE,
                                                           CONSTRAINT `fk_participation_competition1`
                                                               FOREIGN KEY (`competition_id`)
                                                                   REFERENCES `sportcity`.`competition` (`id`)
                                                                   ON DELETE CASCADE
                                                                   ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`organizer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`organizer` (
                                                       `id` INT NOT NULL AUTO_INCREMENT,
                                                       `name` VARCHAR(100) NOT NULL,
                                                       PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`arrangement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`arrangement` (
                                                         `competition_id` INT NOT NULL,
                                                         `organizer_id` INT NOT NULL,
                                                         PRIMARY KEY (`competition_id`, `organizer_id`),
                                                         INDEX `fk_arrangement_organizer1_idx` (`organizer_id` ASC) ,
                                                         CONSTRAINT `fk_arrangement_competition1`
                                                             FOREIGN KEY (`competition_id`)
                                                                 REFERENCES `sportcity`.`competition` (`id`)
                                                                 ON DELETE CASCADE
                                                                 ON UPDATE CASCADE,
                                                         CONSTRAINT `fk_arrangement_organizer1`
                                                             FOREIGN KEY (`organizer_id`)
                                                                 REFERENCES `sportcity`.`organizer` (`id`)
                                                                 ON DELETE CASCADE
                                                                 ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`sport_facilities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`sport_facilities` (
                                                              `id` INT NOT NULL,
                                                              PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`location` (
                                                      `competition_id` INT NOT NULL,
                                                      `sport_facilities_id` INT NOT NULL,
                                                      PRIMARY KEY (`competition_id`, `sport_facilities_id`),
                                                      INDEX `fk_location_sports_facility1_idx` (`sport_facilities_id` ASC) ,
                                                      CONSTRAINT `fk_location_competition1`
                                                          FOREIGN KEY (`competition_id`)
                                                              REFERENCES `sportcity`.`competition` (`id`)
                                                              ON DELETE CASCADE
                                                              ON UPDATE CASCADE,
                                                      CONSTRAINT `fk_location_sports_facility1`
                                                          FOREIGN KEY (`sport_facilities_id`)
                                                              REFERENCES `sportcity`.`sport_facilities` (`id`)
                                                              ON DELETE CASCADE
                                                              ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`stadium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`stadium` (
                                                     `id` INT NOT NULL,
                                                     `capacity` INT NOT NULL,
                                                     PRIMARY KEY (`id`),
                                                     CONSTRAINT `fk_stadium_sports_facility1`
                                                         FOREIGN KEY (`id`)
                                                             REFERENCES `sportcity`.`sport_facilities` (`id`)
                                                             ON DELETE CASCADE
                                                             ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`court`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`court` (
                                                   `id` INT NOT NULL,
                                                   `coverage_type` ENUM('grass', 'clay') NOT NULL,
                                                   PRIMARY KEY (`id`),
                                                   CONSTRAINT `fk_court_sports_facility1`
                                                       FOREIGN KEY (`id`)
                                                           REFERENCES `sportcity`.`sport_facilities` (`id`)
                                                           ON DELETE CASCADE
                                                           ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`mentoring`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`mentoring` (
                                                       `sportsman_id` INT NOT NULL,
                                                       `coach_id` INT NOT NULL,
                                                       PRIMARY KEY (`sportsman_id`, `coach_id`),
                                                       INDEX `fk_mentoring_coach1_idx` (`coach_id` ASC) ,
                                                       CONSTRAINT `fk_mentoring_sportsman1`
                                                           FOREIGN KEY (`sportsman_id`)
                                                               REFERENCES `sportcity`.`sportsman` (`id`)
                                                               ON DELETE CASCADE
                                                               ON UPDATE CASCADE,
                                                       CONSTRAINT `fk_mentoring_coach1`
                                                           FOREIGN KEY (`coach_id`)
                                                               REFERENCES `sportcity`.`coach` (`id`)
                                                               ON DELETE CASCADE
                                                               ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`ice_arena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`ice_arena` (
                                                       `id` INT NOT NULL,
                                                       `square` INT NOT NULL,
                                                       PRIMARY KEY (`id`),
                                                       CONSTRAINT `fk_ice_arena_sports_facility1`
                                                           FOREIGN KEY (`id`)
                                                               REFERENCES `sportcity`.`sport_facilities` (`id`)
                                                               ON DELETE CASCADE
                                                               ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`volleyball_arena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`volleyball_arena` (
                                                              `id` INT NOT NULL,
                                                              `net_height` INT NOT NULL,
                                                              `net_width` INT NOT NULL,
                                                              PRIMARY KEY (`id`),
                                                              CONSTRAINT `fk_volleyball_arena_sports_facility1`
                                                                  FOREIGN KEY (`id`)
                                                                      REFERENCES `sportcity`.`sport_facilities` (`id`)
                                                                      ON DELETE CASCADE
                                                                      ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`abilities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`abilities` (
                                                       `id` INT NOT NULL AUTO_INCREMENT,
                                                       `sportsman_id` INT NOT NULL,
                                                       `category` INT NOT NULL,
                                                       `sport` ENUM('football', 'tennis', 'hockey', 'volleyball', 'figureSkating', 'athletics') NOT NULL,
                                                       PRIMARY KEY (`id`),
                                                       INDEX `fk_abilities_sportsman1_idx` (`sportsman_id` ASC) ,
                                                       CONSTRAINT `fk_abilities_sportsman1`
                                                           FOREIGN KEY (`sportsman_id`)
                                                               REFERENCES `sportcity`.`sportsman` (`id`)
                                                               ON DELETE CASCADE
                                                               ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcity`.`prizewinner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportcity`.`prizewinner` (
                                                         `sportsman_id` INT NOT NULL,
                                                         `competition_id` INT NOT NULL,
                                                         PRIMARY KEY (`sportsman_id`, `competition_id`),
                                                         INDEX `fk_sportsman_has_competition_competition1_idx` (`competition_id` ASC) ,
                                                         INDEX `fk_sportsman_has_competition_sportsman1_idx` (`sportsman_id` ASC) ,
                                                         CONSTRAINT `fk_sportsman_has_competition_sportsman1`
                                                             FOREIGN KEY (`sportsman_id`)
                                                                 REFERENCES `sportcity`.`sportsman` (`id`)
                                                                 ON DELETE CASCADE
                                                                 ON UPDATE CASCADE,
                                                         CONSTRAINT `fk_sportsman_has_competition_competition1`
                                                             FOREIGN KEY (`competition_id`)
                                                                 REFERENCES `sportcity`.`competition` (`id`)
                                                                 ON DELETE CASCADE
                                                                 ON UPDATE CASCADE)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;